#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pycups
Version  : 2.0.1
Release  : 4
URL      : https://files.pythonhosted.org/packages/0c/bb/82546806a86dc16f5eeb76f62ffdc42cce3d43aacd4e25a8b5300eec0263/pycups-2.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/0c/bb/82546806a86dc16f5eeb76f62ffdc42cce3d43aacd4e25a8b5300eec0263/pycups-2.0.1.tar.gz
Summary  : Python bindings for libcups
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: pypi-pycups-filemap = %{version}-%{release}
Requires: pypi-pycups-lib = %{version}-%{release}
Requires: pypi-pycups-license = %{version}-%{release}
Requires: pypi-pycups-python = %{version}-%{release}
Requires: pypi-pycups-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : cups-dev
BuildRequires : python3-dev

%description
CUPS project.
        
        >>> # Example of getting a list of printers
        >>> import cups
        >>> conn = cups.Connection ()
        >>> printers = conn.getPrinters ()

%package filemap
Summary: filemap components for the pypi-pycups package.
Group: Default

%description filemap
filemap components for the pypi-pycups package.


%package lib
Summary: lib components for the pypi-pycups package.
Group: Libraries
Requires: pypi-pycups-license = %{version}-%{release}
Requires: pypi-pycups-filemap = %{version}-%{release}

%description lib
lib components for the pypi-pycups package.


%package license
Summary: license components for the pypi-pycups package.
Group: Default

%description license
license components for the pypi-pycups package.


%package python
Summary: python components for the pypi-pycups package.
Group: Default
Requires: pypi-pycups-python3 = %{version}-%{release}

%description python
python components for the pypi-pycups package.


%package python3
Summary: python3 components for the pypi-pycups package.
Group: Default
Requires: pypi-pycups-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(pycups)

%description python3
python3 components for the pypi-pycups package.


%prep
%setup -q -n pycups-2.0.1
cd %{_builddir}/pycups-2.0.1
pushd ..
cp -a pycups-2.0.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656397323
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pycups
cp %{_builddir}/pycups-2.0.1/COPYING %{buildroot}/usr/share/package-licenses/pypi-pycups/4cc77b90af91e615a64ae04893fdffa7939db84c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-pycups

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pycups/4cc77b90af91e615a64ae04893fdffa7939db84c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
